extends: eslint:recommended
env:
  mocha: true
  node: true
  es6: true
rules:
  comma-dangle: error
  eol-last: error
  eqeqeq: error
  indent:
    - error
    - 2
    - SwitchCase: 1
  no-empty: off
  no-multiple-empty-lines:
    - error
    - max: 1
      maxEOF: 0
      maxBOF: 0
  no-tabs: error
  no-trailing-spaces: error
  object-curly-spacing:
    - error
    - always
  quotes:
    - error
    - single
    - avoid-escape
  semi:
    - error
    - always
